-- MySQL Script generated by MySQL Workbench
-- 03/04/17 10:53:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eaters
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eaters
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eaters` DEFAULT CHARACTER SET utf8 ;
USE `eaters` ;

-- -----------------------------------------------------
-- Table `eaters`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`categorie` (
  `idCategorie` INT(11) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idCategorie`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`client` (
  `idClient` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NULL DEFAULT NULL,
  `prenom` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(30) NULL DEFAULT NULL,
  `telephone` VARCHAR(15) NULL DEFAULT NULL,
  `dateInscription` DATE NOT NULL,
  `adresse` VARCHAR(45) NULL DEFAULT NULL,
  `dateNaissance` DATE NULL DEFAULT NULL,
  `sexe` ENUM('M', 'F') NULL DEFAULT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`plat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`plat` (
  `idPlat` INT(11) NOT NULL,
  `idCategorie` INT(11) NOT NULL,
  `nom` VARCHAR(25) NOT NULL,
  `prix` DOUBLE NULL DEFAULT NULL,
  `dateIntronisation` DATE NULL DEFAULT NULL,
  `quantiteVendue` INT(11) NULL DEFAULT '0',
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  `tempsPreparation` INT(11) NULL DEFAULT NULL,
  `disponible` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idPlat`),
  INDEX `fk_Plat_Categorie1_idx` (`idCategorie` ASC),
  CONSTRAINT `fk_Plat_Categorie1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `eaters`.`categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`commander`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`commander` (
  `idClient` INT(11) NOT NULL,
  `idPlat` INT(11) NOT NULL,
  `dateCommande` DATE NULL DEFAULT NULL,
  `quantite` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idClient`, `idPlat`),
  INDEX `fk_Client_has_Plat_Plat1_idx` (`idPlat` ASC),
  INDEX `fk_Client_has_Plat_Client1_idx` (`idClient` ASC),
  CONSTRAINT `fk_Client_has_Plat_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `eaters`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Plat_Plat1`
    FOREIGN KEY (`idPlat`)
    REFERENCES `eaters`.`plat` (`idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`compte` (
  `idCompte` INT(11) NOT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `pin` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idCompte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`ingredient` (
  `idIngredient` INT(11) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `quantite` INT(11) NULL DEFAULT '0',
  `prochaineDatePeremption` DATE NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `calorie` INT(11) NULL DEFAULT NULL,
  `proteine` INT(11) NULL DEFAULT NULL,
  `glucide` INT(11) NULL DEFAULT NULL,
  `lipide` INT(11) NULL DEFAULT NULL,
  `prixAchat` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idIngredient`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`contient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`contient` (
  `idIngredient` INT(11) NOT NULL,
  `idPlat` INT(11) NOT NULL,
  `quantite` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idIngredient`, `idPlat`),
  INDEX `fk_Ingredient_has_Plat_Plat1_idx` (`idPlat` ASC),
  INDEX `fk_Ingredient_has_Plat_Ingredient1_idx` (`idIngredient` ASC),
  CONSTRAINT `fk_Ingredient_has_Plat_Ingredient1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `eaters`.`ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredient_has_Plat_Plat1`
    FOREIGN KEY (`idPlat`)
    REFERENCES `eaters`.`plat` (`idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`fonction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`fonction` (
  `idfunction` INT(11) NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idfunction`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`employee` (
  `idEmployee` INT(11) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `idFunction` INT(11) NOT NULL,
  `dateNaissance` DATE NULL DEFAULT NULL,
  `dateEmbauche` DATE NULL DEFAULT NULL,
  `salaire` DOUBLE NULL DEFAULT NULL,
  `salaireVersee` TINYINT(1) NULL DEFAULT '0',
  `sexe` ENUM('M', 'F') NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `adresse` VARCHAR(45) NULL DEFAULT NULL,
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  `derniereEvaluation` DOUBLE NULL DEFAULT NULL,
  `idCompte` INT(11) NOT NULL,
  PRIMARY KEY (`idEmployee`),
  INDEX `fk_Employee_Fonction1_idx` (`idFunction` ASC),
  INDEX `fk_Employee_Compte1_idx` (`idCompte` ASC),
  CONSTRAINT `fk_Employee_Compte1`
    FOREIGN KEY (`idCompte`)
    REFERENCES `eaters`.`compte` (`idCompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Fonction1`
    FOREIGN KEY (`idFunction`)
    REFERENCES `eaters`.`fonction` (`idfunction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`tag` (
  `idtag` INT(11) NOT NULL,
  `nom` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtag`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eaters`.`tagged`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eaters`.`tagged` (
  `idTag` INT(11) NOT NULL,
  `idPlat` INT(11) NOT NULL,
  PRIMARY KEY (`idTag`, `idPlat`),
  INDEX `fk_tag_has_Plat_Plat1_idx` (`idPlat` ASC),
  INDEX `fk_tag_has_Plat_tag1_idx` (`idTag` ASC),
  CONSTRAINT `fk_tag_has_Plat_Plat1`
    FOREIGN KEY (`idPlat`)
    REFERENCES `eaters`.`plat` (`idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_has_Plat_tag1`
    FOREIGN KEY (`idTag`)
    REFERENCES `eaters`.`tag` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
