-- MySQL Script generated by MySQL Workbench
-- 03/06/17 21:43:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema koala
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema koala
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `koala` DEFAULT CHARACTER SET utf8 ;
USE `koala` ;

-- -----------------------------------------------------
-- Table `koala`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`categorie` (
  `idCategorie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategorie`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`client` (
  `idClient` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telephone` VARCHAR(15) NULL DEFAULT NULL,
  `dateInscription` DATE NULL,
  `adresse` VARCHAR(255) NULL DEFAULT NULL,
  `dateNaissance` DATE NULL DEFAULT NULL,
  `sexe` ENUM('M', 'F') NULL DEFAULT 'F',
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`plat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`plat` (
  `idPlat` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCategorie` INT UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prix` DOUBLE NULL DEFAULT NULL,
  `dateIntronisation` DATE NULL DEFAULT NULL,
  `quantiteVendue` INT NULL DEFAULT 0,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  `tempsPreparation` INT NULL DEFAULT NULL,
  `disponible` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idPlat`),
  INDEX `fk_Plat_Categorie1_idx` (`idCategorie` ASC),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC),
  CONSTRAINT `fk_Plat_Categorie1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `koala`.`categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`commande` (
  `idCommande` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dateCommande` DATE NULL DEFAULT NULL,
  `modePaiement` ENUM('cache', 'CB', 'cheque', 'bon') NULL,
  `idClient` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCommande`),
  INDEX `fk_commande_client1_idx` (`idClient` ASC),
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `koala`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`commandeUnitaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`commandeUnitaire` (
  `quantite` INT UNSIGNED NULL DEFAULT 0,
  `idPlat` INT UNSIGNED NOT NULL,
  `idCommande` INT UNSIGNED NOT NULL,
  INDEX `fk_commandeUnitaire_plat1_idx` (`idPlat` ASC),
  INDEX `fk_commandeUnitaire_commande1_idx` (`idCommande` ASC),
  PRIMARY KEY (`idPlat`, `idCommande`),
  CONSTRAINT `fk_commandeUnitaire_plat1`
    FOREIGN KEY (`idPlat`)
    REFERENCES `koala`.`plat` (`idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandeUnitaire_commande1`
    FOREIGN KEY (`idCommande`)
    REFERENCES `koala`.`commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`fonction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`fonction` (
  `idFonction` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idFonction`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`employe` (
  `idEmployee` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idFonction` INT UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `sexe` ENUM('M', 'F') NULL DEFAULT NULL,
  `dateNaissance` DATE NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  `adresse` VARCHAR(255) NULL DEFAULT NULL,
  `numeroSecuriteSociale` VARCHAR(45) NULL,
  `dateEmbauche` DATE NULL DEFAULT NULL,
  `image` LONGBLOB NULL,
  `derniereEvaluation` DOUBLE NULL DEFAULT NULL,
  `salaire` DOUBLE NULL DEFAULT NULL,
  `salaireAnnuel` DOUBLE NULL,
  `salaireVerse` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idEmployee`),
  INDEX `fk_Employee_Fonction1_idx` (`idFonction` ASC),
  CONSTRAINT `fk_Employee_Fonction1`
    FOREIGN KEY (`idFonction`)
    REFERENCES `koala`.`fonction` (`idFonction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`compte` (
  `idCompte` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idEmployee` INT UNSIGNED NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `pin` VARCHAR(8) NULL,
  `pinEnabled` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idCompte`),
  INDEX `fk_compte_employee1_idx` (`idEmployee` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_compte_employee1`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `koala`.`employe` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`ingredient` (
  `idIngredient` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `quantite` INT NULL DEFAULT '0',
  `prochaineDatePeremption` DATE NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `calorie` DOUBLE NULL DEFAULT NULL,
  `proteine` DOUBLE NULL DEFAULT NULL,
  `glucide` DOUBLE NULL DEFAULT NULL,
  `lipide` DOUBLE NULL DEFAULT NULL,
  `gluten` TINYINT(1) NULL,
  `prixAchat` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idIngredient`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`contient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`contient` (
  `idIngredient` INT UNSIGNED NOT NULL,
  `idPlat` INT UNSIGNED NOT NULL,
  `quantite` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idIngredient`, `idPlat`),
  INDEX `fk_Ingredient_has_Plat_Plat1_idx` (`idPlat` ASC),
  INDEX `fk_Ingredient_has_Plat_Ingredient1_idx` (`idIngredient` ASC),
  CONSTRAINT `fk_Ingredient_has_Plat_Ingredient1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `koala`.`ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredient_has_Plat_Plat1`
    FOREIGN KEY (`idPlat`)
    REFERENCES `koala`.`plat` (`idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`tag` (
  `idTag` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idTag`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`tagged`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`tagged` (
  `idTag` INT UNSIGNED NOT NULL,
  `idPlat` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTag`, `idPlat`),
  INDEX `fk_tag_has_Plat_Plat1_idx` (`idPlat` ASC),
  INDEX `fk_tag_has_Plat_tag1_idx` (`idTag` ASC),
  CONSTRAINT `fk_tag_has_Plat_Plat1`
    FOREIGN KEY (`idPlat`)
    REFERENCES `koala`.`plat` (`idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_has_Plat_tag1`
    FOREIGN KEY (`idTag`)
    REFERENCES `koala`.`tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `koala`.`compteClient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koala`.`compteClient` (
  `idCompte` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idClient` INT UNSIGNED NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `pinEnabled` TINYINT(1) NULL DEFAULT 0,
  `pin` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`idCompte`),
  INDEX `fk_compteClient_client1_idx` (`idClient` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_compteClient_client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `koala`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
